//! Exact full-receipt artifact closures; source and field identities remain explicit.
use crate::source_inventory::{
    CYCLOTOMIC, FIXED_PAIR, FP, FP2, G1_VALIDATION, MILLER_CORE, Source,
};
pub(crate) const RECEIPT: &[Source] = &[
    FP,
    FP2,
    G1_VALIDATION,
    CYCLOTOMIC,
    MILLER_CORE,
    Source {
        filename: "verification_key.ral",
        origin: "l2/contracts/alephium/verifier/verification_key.ral",
        contract: "Risc0VerificationKey",
        bytes: include_bytes!("../../contracts/alephium/verifier/verification_key.ral"),
    },
    Source {
        filename: "g1.ral",
        origin: "l2/contracts/alephium/verifier/g1.ral",
        contract: "Bn254G1",
        bytes: include_bytes!("../../contracts/alephium/verifier/g1.ral"),
    },
    Source {
        filename: "fp6.ral",
        origin: "l2/contracts/alephium/verifier/fp6.ral",
        contract: "Bn254Fp6",
        bytes: include_bytes!("../../contracts/alephium/verifier/fp6.ral"),
    },
    Source {
        filename: "fp12.ral",
        origin: "l2/contracts/alephium/verifier/fp12.ral",
        contract: "Bn254Fp12",
        bytes: include_bytes!("../../contracts/alephium/verifier/fp12.ral"),
    },
    Source {
        filename: "frobenius.ral",
        origin: "l2/contracts/alephium/verifier/frobenius.ral",
        contract: "Bn254Frobenius",
        bytes: include_bytes!("../../contracts/alephium/verifier/frobenius.ral"),
    },
    Source {
        filename: "exponent.ral",
        origin: "l2/contracts/alephium/verifier/exponent.ral",
        contract: "Bn254Exponent",
        bytes: include_bytes!("../../contracts/alephium/verifier/exponent.ral"),
    },
    Source {
        filename: "sparse.ral",
        origin: "l2/contracts/alephium/verifier/sparse.ral",
        contract: "Bn254Sparse",
        bytes: include_bytes!("../../contracts/alephium/verifier/sparse.ral"),
    },
    Source {
        filename: "g2.ral",
        origin: "l2/contracts/alephium/verifier/g2.ral",
        contract: "Bn254G2",
        bytes: include_bytes!("../../contracts/alephium/verifier/g2.ral"),
    },
    Source {
        filename: "g2_subgroup.ral",
        origin: "l2/contracts/alephium/verifier/g2_subgroup.ral",
        contract: "Bn254G2Subgroup",
        bytes: include_bytes!("../../contracts/alephium/verifier/g2_subgroup.ral"),
    },
    Source {
        filename: "miller_lines.ral",
        origin: "l2/contracts/alephium/verifier/miller_lines.ral",
        contract: "Bn254MillerLines",
        bytes: include_bytes!("../../contracts/alephium/verifier/miller_lines.ral"),
    },
    Source {
        filename: "miller_engine.ral",
        origin: "l2/contracts/alephium/verifier/miller_engine.ral",
        contract: "Bn254MillerEngine",
        bytes: include_bytes!("../../contracts/alephium/verifier/miller_engine.ral"),
    },
    Source {
        filename: "receipt_claims.ral",
        origin: "l2/contracts/alephium/verifier/receipt_claims.ral",
        contract: "Risc0ReceiptClaims",
        bytes: include_bytes!("../../contracts/alephium/verifier/receipt_claims.ral"),
    },
    Source {
        filename: "receipt.ral",
        origin: "l2/contracts/alephium/verifier/receipt.ral",
        contract: "Risc0ReceiptVerifier",
        bytes: include_bytes!("../../contracts/alephium/verifier/receipt.ral"),
    },
];

pub(crate) const RESIDUE_RECEIPT: &[Source] = &[
    FP,
    FP2,
    G1_VALIDATION,
    MILLER_CORE,
    FIXED_PAIR,
    Source {
        filename: "verification_key.ral",
        origin: "l2/contracts/alephium/verifier/verification_key.ral",
        contract: "Risc0VerificationKey",
        bytes: include_bytes!("../../contracts/alephium/verifier/verification_key.ral"),
    },
    Source {
        filename: "g1.ral",
        origin: "l2/contracts/alephium/verifier/g1.ral",
        contract: "Bn254G1",
        bytes: include_bytes!("../../contracts/alephium/verifier/g1.ral"),
    },
    Source {
        filename: "fp6.ral",
        origin: "l2/contracts/alephium/verifier/fp6.ral",
        contract: "Bn254Fp6",
        bytes: include_bytes!("../../contracts/alephium/verifier/fp6.ral"),
    },
    Source {
        filename: "fp12.ral",
        origin: "l2/contracts/alephium/verifier/fp12.ral",
        contract: "Bn254Fp12",
        bytes: include_bytes!("../../contracts/alephium/verifier/fp12.ral"),
    },
    Source {
        filename: "frobenius.ral",
        origin: "l2/contracts/alephium/verifier/frobenius.ral",
        contract: "Bn254Frobenius",
        bytes: include_bytes!("../../contracts/alephium/verifier/frobenius.ral"),
    },
    Source {
        filename: "sparse.ral",
        origin: "l2/contracts/alephium/verifier/sparse.ral",
        contract: "Bn254Sparse",
        bytes: include_bytes!("../../contracts/alephium/verifier/sparse.ral"),
    },
    Source {
        filename: "g2.ral",
        origin: "l2/contracts/alephium/verifier/g2.ral",
        contract: "Bn254G2",
        bytes: include_bytes!("../../contracts/alephium/verifier/g2.ral"),
    },
    Source {
        filename: "g2_subgroup.ral",
        origin: "l2/contracts/alephium/verifier/g2_subgroup.ral",
        contract: "Bn254G2Subgroup",
        bytes: include_bytes!("../../contracts/alephium/verifier/g2_subgroup.ral"),
    },
    Source {
        filename: "miller_lines.ral",
        origin: "l2/contracts/alephium/verifier/miller_lines.ral",
        contract: "Bn254MillerLines",
        bytes: include_bytes!("../../contracts/alephium/verifier/miller_lines.ral"),
    },
    Source {
        filename: "receipt_claims.ral",
        origin: "l2/contracts/alephium/verifier/receipt_claims.ral",
        contract: "Risc0ReceiptClaims",
        bytes: include_bytes!("../../contracts/alephium/verifier/receipt_claims.ral"),
    },
    Source {
        filename: "residue_miller.ral",
        origin: "l2/contracts/alephium/verifier/residue_miller.ral",
        contract: "Bn254ResidueMiller",
        bytes: include_bytes!("../../contracts/alephium/verifier/residue_miller.ral"),
    },
    Source {
        filename: "receipt_residue.ral",
        origin: "l2/contracts/alephium/verifier/receipt_residue.ral",
        contract: "Risc0ResidueReceiptVerifier",
        bytes: include_bytes!("../../contracts/alephium/verifier/receipt_residue.ral"),
    },
];

pub(crate) const RESIDUE_DIAGNOSTIC: &[Source] = &[
    FP,
    FP2,
    G1_VALIDATION,
    MILLER_CORE,
    FIXED_PAIR,
    Source {
        filename: "verification_key.ral",
        origin: "l2/contracts/alephium/verifier/verification_key.ral",
        contract: "Risc0VerificationKey",
        bytes: include_bytes!("../../contracts/alephium/verifier/verification_key.ral"),
    },
    Source {
        filename: "g1.ral",
        origin: "l2/contracts/alephium/verifier/g1.ral",
        contract: "Bn254G1",
        bytes: include_bytes!("../../contracts/alephium/verifier/g1.ral"),
    },
    Source {
        filename: "fp6.ral",
        origin: "l2/contracts/alephium/verifier/fp6.ral",
        contract: "Bn254Fp6",
        bytes: include_bytes!("../../contracts/alephium/verifier/fp6.ral"),
    },
    Source {
        filename: "fp12.ral",
        origin: "l2/contracts/alephium/verifier/fp12.ral",
        contract: "Bn254Fp12",
        bytes: include_bytes!("../../contracts/alephium/verifier/fp12.ral"),
    },
    Source {
        filename: "frobenius.ral",
        origin: "l2/contracts/alephium/verifier/frobenius.ral",
        contract: "Bn254Frobenius",
        bytes: include_bytes!("../../contracts/alephium/verifier/frobenius.ral"),
    },
    Source {
        filename: "sparse.ral",
        origin: "l2/contracts/alephium/verifier/sparse.ral",
        contract: "Bn254Sparse",
        bytes: include_bytes!("../../contracts/alephium/verifier/sparse.ral"),
    },
    Source {
        filename: "g2.ral",
        origin: "l2/contracts/alephium/verifier/g2.ral",
        contract: "Bn254G2",
        bytes: include_bytes!("../../contracts/alephium/verifier/g2.ral"),
    },
    Source {
        filename: "g2_subgroup.ral",
        origin: "l2/contracts/alephium/verifier/g2_subgroup.ral",
        contract: "Bn254G2Subgroup",
        bytes: include_bytes!("../../contracts/alephium/verifier/g2_subgroup.ral"),
    },
    Source {
        filename: "miller_lines.ral",
        origin: "l2/contracts/alephium/verifier/miller_lines.ral",
        contract: "Bn254MillerLines",
        bytes: include_bytes!("../../contracts/alephium/verifier/miller_lines.ral"),
    },
    Source {
        filename: "receipt_claims.ral",
        origin: "l2/contracts/alephium/verifier/receipt_claims.ral",
        contract: "Risc0ReceiptClaims",
        bytes: include_bytes!("../../contracts/alephium/verifier/receipt_claims.ral"),
    },
    Source {
        filename: "residue_miller.ral",
        origin: "l2/contracts/alephium/verifier/residue_miller.ral",
        contract: "Bn254ResidueMiller",
        bytes: include_bytes!("../../contracts/alephium/verifier/residue_miller.ral"),
    },
    Source {
        filename: "residue-diagnostic.ral",
        origin: "l2/verifier-tool/fixtures/residue-diagnostic.ral",
        contract: "Risc0ResidueDiagnostics",
        bytes: include_bytes!("../fixtures/residue-diagnostic.ral"),
    },
];
